require 'plugins'
require 'mason-config'
require 'setter'
require 'nvim-cmp-config'
require 'nvim-tree-config'
require 'lualine-config'
require 'bufferline-config'
require 'smooth-scroll-config'
require 'treesitter-config'
require 'telescope-config'
require 'mapping'
require 'nvim-dap'
require 'neoformat-config'

vim.cmd("colorscheme ayu-dark")
